cmd/root.go
Needs a redesign. Will be added back later.
=> Disable daemon command for now.

go.mod, go.sum, trace/obfuscate.go
Depends on akitasoftware/akita-libs#25.
=> Bump akita-libs for diff visitors.

cmd/internal/ci_guard/guard.go, cmd/root.go
=> Add flag for disabling the GitHub teams check

pcap/net_parse.go
Do not run Flush() in a defer that might be run as a result of a panic
inside the FlushCloseOlderThan() call. The gopacket code does not use
defer'ed unlocks consistently (and even without that consideration, the
state may well be inconsistent.)
Backtrace from one of the deadlocks (they appear to have hit nearly every capture agent, but I did not check that they are all the same.)
```
0  0x000000000043a5e5 in runtime.gopark
at .usr/local/go/src/runtime/proc.go:337
1  0x000000000044b765 in runtime.goparkunlock
at .usr/local/go/src/runtime/proc.go:342
2  0x000000000044b765 in runtime.semacquire1
at .usr/local/go/src/runtime/sema.go:144
3  0x000000000046b087 in sync.runtime_SemacquireMutex
at .usr/local/go/src/runtime/sema.go:71
4  0x0000000000487f65 in sync.(*Mutex).lockSlow
at …
```
=> Fix deadlock on reassembly segfault

apidump/apidump.go
Unfortunately, this probably won't compile on Windows because it doesn't have SIGTERM?
The os package only has Interrupt and Kill aliases defined.
=> Handle SIGTERM by gracefully shutting down trace.

cmd/internal/upload/cmd.go
The upload library took a Plugins argument, but it was not filled in by the command.
=> Use plugins for upload.

apidump/apidump.go
Ignore any empty regexes for including/excluding hosts and paths. Print a warning when this happens.
=> Lint include/exclude regexes

apidump/apidump.go, cmd/internal/get/graph.go, go.mod, go.sum, tls_conn_tracker/tls_conn_tracker.go, trace/backend_collector.go, trace/collector.go, trace/run.go
Parse TLS handshakes and report them to the back end.
Augmented the service graph with TLS edges, detailing the TLS version and application-layer protocol, if known.
=> Initial TLS support

cmd/internal/ascii/cmd.go, cmd/root.go
```
mark@ubuntu:~/akita-cli$ bin/akita aki
___                 ___
>_ \   _ _ _ _ _   / _<
< <, Y``         ''Y .> >
\ (`  .-.-._.-.-.  ') /
( ` .'  _     _  `. ' )
)  (   (')___(')   )  ( 
(  ('      `Y'      `)  )
(   (.  `.__|__.'  .)   )
(.  (._         _.)  .)
(_   `- - - - -'   _)
`-._ _ ___ _ _.-´  
```
=> Add "akita aki" command

.circleci/config.yml
Also update apt repos before installing packages.
=> Update docker image for CI

.gitignore, apidump/apidump.go, apidump/summary.go, daemon/internal/cloud_client/cloud_client.go, go.mod, go.sum, rest/interface.go, rest/learn_client.go, trace/collector.go, trace/run.go, trace/stats.go, trace/stats_test.go, upload/run.go
Depends on https://github.com/akitasoftware/akita-libs/pull/142.
=> Send debugging telemetry to the backend

pcap/net_parse.go
This covers the known bug... but, it's not clear whether the
reassembly layer can successfully recover afterwards, or if additional
cleanup is needed.
=> Catch panics during packet reassembly.

apidump/apidump.go
Noticed this while watching the integration tests run
=> Fix error output from telemetry

apidump/apidump.go, go.mod, go.sum
Made a start at refactoring apidump.Run() into smaller methods.
Update akita-libs.
=> Send telemetry about startup errors to the backend.

go.mod, go.sum
Bumps akita-libs to fix how cookies are parsed.
=> Fix cookie parsing

cmd/internal/ecs/add.go, cmd/internal/ecs/aws_api_secret.go, cmd/internal/ecs/ecs.go, go.mod, go.sum
...if they do not already exist.
Check that credentials are present and project exists.
=> Create AWS secrets to hold Akita credentials

cmd/internal/ecs/add.go, cmd/internal/ecs/aws_api.go, cmd/internal/ecs/ecs.go
Handle config files in a docker volume named /aws.
Un-hide 'ecs' subcommand.
Added utility function for converting 'arn' type to *string for AWS SDK.
=> Update ECS service and wait for deployment to complete.

trace/collector.go
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203390923946715
=> Don't include traffic to api.akita.software in the count by host.

cmd/internal/nginx/dev_capture.go, cmd/internal/nginx/nginx.go, cmd/root.go
For now this just spits out whatever is sent (and already demonstrated a bug!)
However, it would be better if it also showed buggy requests instead of silently rejecting them.  :(
The commands have bogus names which will be replaced in the real version (to avoid putting everything in a long-lived feature branch.)
=> Add stub NGINX commands, and development-mode server.

cmd/internal/nginx/nginx.go, integrations/nginx/backend.go, integrations/nginx/rest.go
Uses fake port numbers!
Upload some telemetry with packet counts and report on console.
=> Upload witnesses derived from Nginx.

cmd/internal/nginx/nginx.go, integrations/nginx/github.go, integrations/nginx/install.go, telemetry/telemetry.go
Checks Nginx version, architecture, and operating system.
Downloads the file into a temp directory, then moves it to nginx's modules directory and creates a symbolic link.
=> Install a precompiled module from the latest Github release.

cmd/internal/get/traces.go, cmd/internal/legacy/sessions_list.go, rest/base_client.go, rest/front_client.go, rest/interface.go, rest/learn_client.go, util/util.go
* Export base HTTP client to make it available for external use.
* Expose pagination in ListLearnSessions.
=> Interface tweaks

cfg/credentials.go, rest/http.go
In this PR we have done following changes:
* Add support for Postman API Key and Environment in akita-cli
* Refactored the `credentials.go` to remove duplicate code
* New functions to read/write Postman API Key and Environment
* Added a check in `http.go` to chose between Akita auth or Postman auth based on the configuration
* Some small type fixes
=> [OBS-35] Add support for postman api key

apidump/apidump.go, cfg/credentials.go, cmd/internal/apidump/apidump.go, cmd/internal/cmderr/checks.go, cmd/internal/ecs/ecs.go, cmd/internal/kube/inject.go, cmd/internal/kube/secret.go, cmd/internal/kube/secret_test.go, cmd/internal/kube/template/postman-secret.tmpl, cmd/internal/kube/test_resource/postman-secret.yml, rest/base_client.go, rest/http.go
* Add support for 3 Postman flags in `apidump` command, namely `--collection`, `--key `, and `--environment`
* Get the correct serviceID based on the passed Postman collectionID
=> [OBS-36] Add postman flags support in `apidump`

rest/front_client.go, rest/interface.go, util/util.go
In this PR we have added support for the following:
* Ability to create service in Akita BE if the request is coming for postman agent
* Add env var in caching along with `collectionId`
* We are using random name for `serviceName`
=> [OBS-83] Create mirror service from cli

apidump/apidump.go, cfg/credentials.go, cmd/internal/apidump/apidump.go, cmd/internal/cmderr/checks.go, cmd/internal/ecs/ecs.go, cmd/internal/kube/inject.go, cmd/internal/kube/secret.go, cmd/internal/kube/secret_test.go, cmd/internal/kube/template/postman-secret.tmpl, cmd/internal/kube/test_resource/postman-secret.yml, rest/base_client.go, rest/front_client.go, rest/http.go, rest/interface.go, rest/models.go, util/util.go
* In this PR we are adding a util function to get the Akita ServiceID from Postman CollectionID.
* Added PostmanMetaData in the rest model.
* Checking for the collectionID from the list of services.
* Added in memory cache for storing mapping between Akita serviceID and Postman CollectionID
=> [OBS-39] Add util function to get Akita ServiceID from Postman CollectionID

apidump/net.go, cmd/internal/ecs/add.go, cmd/internal/nginx/nginx.go, telemetry/telemetry.go
This PR replaces `support@akitasoftware.com` with `observability-support@postman.com` in messages sent from the CLI
=> [OBS-118] Update support email

cmd/internal/ecs/README.md
=> [DOC] Readme editorial update

cmd/internal/ecs/add.go
This was causing failures on an EC2-based cluster where only container memory sizes were being used.
=> Specify a container memory size when the task does not have one.

rest/front_client.go, rest/interface.go, rest/models.go, telemetry/telemetry.go, util/util.go
* Integrated two new endpoints in akita-cli
* Currently they are not in use, will be added in further PRs
=> [POA-731] Integrate new service info and user info endpoints

.github/workflows/security-scan.yaml, .gitignore, Makefile, apidump/net.go, apidump/summary.go, apispec/har.go, cmd/internal/cmderr/checks.go, cmd/internal/ec2/README.md, cmd/internal/ec2/add.go, cmd/internal/ec2/ec2.go, cmd/internal/ec2/postman-insights-agent.service, cmd/internal/ec2/postman-insights-agent.tmpl, cmd/internal/ecs/add.go, cmd/internal/ecs/ecs.go, cmd/internal/kube/inject.go, cmd/internal/kube/kube.go, cmd/root.go, daemon/internal/cloud_client/cloud_client.go, integrations/nginx/schema.go, telemetry/telemetry.go, trace/report_buffer.go, usage/usage.go, useragent/useragent.go, useragent/useragent_test.go
Done changes acc to this: https://postmanlabs.atlassian.net/wiki/spaces/PO/pages/4911792297/Plan+Agent+rebranding#User-visible-strings-in-the-binary
=> [POA-860] Replace postman lc with postman insights
