postmanlabs/observability-cli

- go.mod
- go.sum
- pcap/http_timing_test.go
- pcap/pcap_replay_test.go
- pcap/stream.go
- pcap/stream_test.go
Depends on https://github.com/akitasoftware/akita-libs/pull/12
Previously if a ParsedNetworkTraffic object spanned multiple packets, the timestamp on the first packet was recorded in ObservationTime. This change records the timestamp on the final packet in the sequence as well, which corresponds to the time when a request has completely arrived at a server.
Method signatures have changed to pass the reassembly.AssemblerContext through, which was previously ignored.
> Retain the final timestamp for each request

- apispec/har.go
- apispec/run.go
- cmd/internal/man/upload_page.go
- cmd/internal/upload/cmd.go
- cmd/internal/upload/flags.go
- go.mod
- go.sum
- upload/args.go
- upload/run.go
This adds support for uploading HAR files to the `upload` command. The old `--service` and `--name` options are now deprecated in favour of `--dest`, which takes in Akita URIs.
When uploading traces, the user may provide multiple files to upload to a single trace. Plugins and removal of third-party trackers is supported. If the specified trace already exists, the user must specify `--append` to modify the trace. If `--append` is used when the trace doesn't yet exist, the trace is created and a warning is printed to stderr.
> Add support for uploading HAR files to `upload`

- learn/learn_test.go
- learn/parse_http.go
- learn/parse_http_test.go
- learn/util_test.go
- trace/backend_collector.go
- trace/backend_collector_test.go
Replace map[] with a sync.Map.
Move periodic flush to its own goroutine.
The unit test is not too impressive right now but I intend to use it to test packet count per interface, when that goes in.
> Resolve race conditions in BackendCollector.

- apidump/apidump.go
- apispec/run.go
- go.mod
- go.sum
- pcap/net_parse.go
- trace/backend_collector.go
- trace/run.go
- trace/stats.go
- upload/run.go
Capture packet counts from pcap and parsing layers.
Display this information in summary form in the debug output.
Example output capturing HTTPS:
```
[INFO] Captured 364 TCP packets total; 182 unparsed TCP segments.
[INFO] This may mean you are trying to capture HTTPS traffic.
[INFO] See https://docs.akita.software/docs/proxy-for-encrypted-traffic
[INFO] for instructions on using a proxy, or generate a HAR file with
[INFO] your browser as described in
[INFO] https://docs.akita.software/docs/collect-client-side-traffic-2
[ERROR] No inbound HTTP calls captured! 🛑
[ERROR] failed to create trace: incomping API trace is empty
```
Example output when no traffic on the desired port:
```
[INFO] Did not capture any TCP packets matching the filter.
[INFO] This may mean your filter is incorrect, …
```
> Diagnostic information when trace is empty

- trace/backend_collector.go
- upload/run.go
In-memory buffer is flushed on Close(), or periodically, so < 10 packets
wouldn't have been sent at all-- and larger traces would probably be truncated.
Added debugging information about flushes, and a count of uploaded HTTP packets.
> BackendCollectors should send all requests to server

- daemon/internal/cloud_client/change_active_traces_event.go
- daemon/internal/cloud_client/client_state.go
- daemon/internal/cloud_client/cloud_client.go
- daemon/internal/cloud_client/registration_request.go
- daemon/internal/cloud_client/trace_event_request.go
- daemon/run.go
Bodies of registration requests from middleware now contain just a single JSON object. Previously, it was a stream of objects, which some frameworks (e.g., Express.js) don't appear to support very well.
When sending trace events, middleware now indicate whether to expect more events in future requests.
Wait for middleware to finish sending their events before shutting down a trace.
Instrumented backend collector with a packet count summary. We now report the number of requests and responses uploaded when shutting down a trace.
Added a missing channel flush.
Added more logging.
> Tweaks to daemon–middleware API.

- daemon/internal/cloud_client/long_poll_service_event.go
- rest/front_client.go
- rest/interface.go
- util/util.go
This allows us to more easily tell which daemon instances are querying for a particular service, so we can show their names to the user in the UI.
> Add daemon_name to long poll request

- trace/backend_collector.go
- trace/backend_collector_test.go
"break" only exits the "select" statement, not the loop.
The loop ran forever busy-waiting because flushDone was always triggered once closed.
> Ensure periodicFlush exits

- daemon/internal/cloud_client/trace_event_request.go
- daemon/run.go
Switch to a *TraceEvent everywhere from demarshaling the incoming message
up to putting it in the channel to send to the cloud.
The problem (and I run into this all the time trying to modify a Go slice) is that
```
for _, traceEvent := range req.traceEvents {
```
does not bind traceEvent to each of the slice elements in turn (like a C++ reference.)  It's just a copy, and moreover a copy in a local variable, so its address is the same each time.
> Fix repeated trace event overriding others in batch

- go.mod
- go.sum
- learn/parse_http.go
- learn/parse_http_test.go
When producing IR from traces, don't auto-convert strings to ints and bools. This was causing us to generate incorrect specs.
> Convert strings in traces to other types depending on context

- cfg/credentials.go
- cmd/internal/login/flags.go
- cmd/internal/login/login.go
Changes:
- `akita login` now tests credentials before reporting success
- `akita login --check` is a new flag that tests existing credentials
> Validate credentials on login

- cmd/internal/man/cmd.go
- cmd/internal/man/setversion_page.go
- cmd/internal/setversion/cmd.go
- cmd/root.go
- go.mod
- go.sum
- rest/learn_client.go
- setversion/args.go
- setversion/run.go
Adds `setversion` for setting version names of API models.
```
Sets the version name for an API model.
Usage:
akita setversion NAME SPEC_AKITA_URI [flags]
Flags:
-h, --help   help for setversion
```
> Add ability to set API-model version names

- apidump/apidump.go
- apispec/run.go
- daemon/internal/cloud_client/cloud_client.go
- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/collector.go
- upload/run.go
This ensures counts are collected whether apidump is using the backend collector or the HAR collector; previously it was giving an error that no packets were detected when writing to a HAR.
> Move packet-counting logic into a shim Collector

- apidump/apidump.go
- apispec/run.go
- cmd/internal/apidump/apidump.go
- cmd/internal/learn/cmd.go
- deployment/deployment.go
- go.mod
- go.sum
I discovered while testing that when using 'learn' that the trace did not have the full set of tags; only the spec did.  I fixed this for deployment; should it also be fixed for CI?
Probably, I think, the automatic tags creation should be done by the original command during command line parsing; having "learn" process the tags twice, once in apidump.Run() and once in apispec.Run() and once in  is a little off.
> Convert environment variables to Kubernetes deployment tags

- daemon/run.go
The daemon cannot be run in a Docker container (even for same-host traffic) if it only listens to address 127.0.0.1.  The traffic from outside the container is destined to the container's address, like 172.17.0.2, so the connection is reset if there is an address mismatch.  e.g., 
```
mark@ubuntu:~/akibox-tutorial$ curl -X POST http://localhost:50080/v1/services/mgg-test/middleware -H "Content-type: application/json" -d '{"client_name" : "mgg_test", "active_trace_ids" : [] }'
curl: (56) Recv failure: Connection reset by peer
```
See https://stackoverflow.com/questions/57773604/connection-reset-by-peer-when-when-hitting-docker-container
> Listen to all local addresses, not just 127.0.0.1

- cmd/internal/upload/cmd.go
- cmd/internal/upload/flags.go
- upload/args.go
- upload/run.go
Allow users to specify tags when uploading specs and traces.
> Add `--tags` to `upload` command

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
- cmd/internal/learn/cmd.go
- cmd/internal/learn/flags.go
- trace/filters.go
Only add filters that are enabled to the stack of collectors.
Add a pre-filter packet count so that we can compare and warn if all
packets we eliminated due to filters.
```
[INFO] Captured 8 HTTP requests before allow and exclude rules, but all were filtered.
[ERROR] No inbound HTTP calls captured! 🛑
```
> Add --allow-host and --allow-path flags

- trace/rate_limit.go
The bug here is that the other side of this channel is read in rateLimitCollector.Process().  It is used to signal the start of a new epoch, so that the collectors have a chance to expire unmatched requests.
But, if there is no traffic on a particular interface for 10 minutes, then that collector's Process() method would never be called and so not clear the channel.  Then startNewEpoch() would block with the lock held.
The fix here is to send to the rate-limited collectors in a nonblocking fashion.  If they aren't receiving packets, then it's not particularly important to expire their request map.  I also decided to do the channel writes without the mutex held.
Verified by letting the CLI run that the new code path is used:
```
[INFO] Running learn mode on interfaces lo, ens33, docker0, …
```
> Signal rate limit collectors in a nonblocking fashion

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
- cmd/internal/apispec/cmd.go
- cmd/internal/apispec/flags.go
- cmd/internal/upload/cmd.go
- cmd/internal/upload/flags.go
- util/util.go
Usage examples
```
akita upload --dest akita://mgg-test:trace --append-by-tag --tags tester=mark foo/akita_lo.har
[INFO] Appending to akita://mgg-test:trace:marsh-wasp-ebb9ec14
[INFO] Uploading "foo/akita_lo.har"...
...
akita apidump --append-by-tag --out akita://mgg-test --filter "port 8000" --tags tester=bob
[INFO] No matching traces found, creating new trace.
[INFO] Created new trace on Akita Cloud: akita://mgg-test:trace:quilt-ape-cddc2f9a
...
akita apidump --service mgg-test --append-by-tag --tags tester=bob
[INFO] Trace akita://mgg-test:trace:quilt-ape-cddc2f9a matches tag
[INFO] Adding to existing trace: akita://mgg-test:trace:quilt-ape-cddc2f9a
...
akita apispec --service mgg-test --trace-tag tester=mark 
[INFO] Trace akita://mgg-test:trace:marsh-wasp-ebb9ec14 matches tag
[INFO] …
```
> Add command-line flags to refer to a trace by tag

- trace/backend_collector.go
This is just a stopgap. We really should be measuring the size of the accumulated payload, not the number of witnesses.
> Increase upload batch size to 120 witnesses

- pcap/stream.go
Have seen the new error messages several times already in prod + staging.
> AssemblerContext is nil for packet started at 2021-07-07 18:44:15.323164 +0000 UTC
> Handle nil AssemblerContext

- apispec/run.go
- cmd/internal/apispec/cmd.go
- cmd/internal/apispec/flags.go
- cmd/internal/man/apispec_page.go
- go.mod
- go.sum
- rest/interface.go
- rest/learn_client.go
This adds `--from-time` and `--to-time` options to `apispec` for filtering which witnesses are included in the generated spec. The intent is for this to filter by the witnesses' observation time. However due to limitations in the current database schema, for witnesses that are observed multiple times, this currently filters on the first time each witness was observed in a learn session. Future back-end improvements will bring these options closer to the intended semantics.
> Add time-bounds options to `apispec`

- cmd/root.go
- go.mod
- pcap/net_parse.go
Depends on https://github.com/akitasoftware/akita-libs/pull/58
Also lowers the stream timeout to 10 seconds, with a flag for configuring it.
> Add hidden flag (and config file entry) for max HTTP length

- cmd/root.go
- go.sum
Example usage:
```
bin/akita apidump --out foo --heap-profile heap.prof --cpu-profile cpu.prof --live-profile localhost:6060
...
go tool pprof http://localhost:6060/debug/pprof/heap
```
> Enable CPU and heap profiling based on command line flags.

- upload/run.go
The CLI output for `akita upload` mixed `info` output on `stderr` and `stdout`, which occasionally caused the formatting to break.  This PR switches to use `stderr` exclusively.
> Fix success message for akita upload cmd

- apispec/run.go
- cmd/internal/apispec/cmd.go
- cmd/internal/apispec/flags.go
- cmd/internal/learn/cmd.go
- cmd/internal/learn/flags.go
- cmd/internal/setversion/cmd.go
- go.mod
- go.sum
- rest/interface.go
- rest/learn_client.go
This PR adds a `--versions` flag to the `apispec` and `learn` commands, which
allows users to assign versions to models at creation time.
Example usage:
* `akita apispec --traces akita://akibox:trace:t1 --versions stable`
* `akita learn --service akibox --versions stable,demo`
> Assign versions on model creation

- cfg/credentials.go
This PR removes a feature that reloads the Akita configuration file on file
change.  There are two reasons to remove this:
1. The config file holds security creds, and the Akita CLI immediately fails
with bad creds.  There's no benefit to reloading on change.
2. The feature -- part of the Viper library -- prints a spurious error message
when the config file is missing but the config values are present in
environment variables.
> Disable config file reloading

- apidump/apidump.go
- apispec/run.go
- cmd/internal/legacy/util.go
- cmd/root.go
- printer/printer.go
- upload/run.go
This isn't a complete solution for DataDog, but I've decided it's worth keeping so we don't wrap ANSI color codes in JSON.
> Use Aurora through printer package. Disable based on --no-color flag.

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
- cmd/internal/apispec/cmd.go
- cmd/internal/get/specs.go
- cmd/internal/get/traces.go
- cmd/internal/learn/cmd.go
- cmd/internal/upload/cmd.go
- cmd/root.go
- go.mod
- go.sum
- printer/printer.go
- util/util.go
Depends on https://github.com/akitasoftware/akita-libs/pull/64 so that the warning message about reserved tags is consistently formatted.
Also, took the opportunity to not log warnings in a couple places where using a reserved tag to filter objects would be OK.
Example output:
```
{"date":"2021-07-29T17:26:26.598170266-05:00","status":"warning","message":"x-akita-source is an Akita-reserved key. Its value may be overwritten internally."}
{"date":"2021-07-29T17:26:26.67969592-05:00","status":"info","message":"Running learn mode on interfaces br-a3f4bbff3da2, lo, ens33, br-1d38328ca3be, docker0, br-75a0084d9170"}
{"date":"2021-07-29T17:26:26.679761692-05:00","status":"warning","message":"--filter flag is not set, this means that:"} …
```
> Add log format argument and JSON log format compatible with DataDog

- go.mod
- go.sum
The is the CLI version of https://github.com/akitasoftware/akita-libs/pull/65
I think we also need to update akita-libs in this repo to point at the one that has been upgraded, once that change has landed.
> Upgrade gopacket to v1.1.19 (+ Akita changes)

- apidump/apidump.go
- learn/learn_runner.go
- pcap/net_parse.go
- pcap/net_parse_test.go
- pcap/pcap_replay_test.go
- trace/run.go
Split the configured page cache size up among the different parsers, one per interface and per direction.
This successfully reduces the memory; we don't have a way to measure what it does to "goodput" or if we lose some packets because we could not buffer enough to see the retransmission.
> Split the maximum page cache size up among each parser.

- apispec/run.go
The `learn` and `apispec` commands currently print the spec ID to stdout on
successful spec creation.  This PR prints the URI rather than the ID, as other
CLI commands require the URI as input.
This makes it possible to script sequences of CLI commands, like `akita learn`
followed by `akita setversion`.
> Print spec URI rather than ID on spec creation

- go.mod
- go.sum
- learn/learn.go
- learn/parse_http.go
- trace/backend_collector.go
Only a small number of places in the CLI that use protohash; replace them by more-specific calls to the new hashing functions.
Depends on https://github.com/akitasoftware/akita-libs/pull/71
> Use improved hashing in CLI

- learn/parse_http.go
- learn/parse_http_test.go
Limit the size of decompressed data than cannot be streamed.
In the future, we might be able to give this layer a HTTP request or response whose body has not yet been completely read.  But,  that would be challenging because the Parser interface can't currently signal "Here's your data, but I'm still reading to keep feeding me bytes."
> Stream decompressed data to a parser instead of buffering it.

- cmd/internal/legacy/checkpoint.go
- cmd/internal/legacy/sessions_checkpoint.go
- cmd/internal/legacy/sessions_create.go
- cmd/internal/legacy/util.go
- rest/interface.go
- rest/learn_client.go
As part of this change, `learn-sessions checkpoint` now creates an API model with a randomly-generated name rather than `""`, matching the behavior of `apispec` when no name is specified.
> Update 'learn-sessions checkpoint' to return URI rather than ID

- learn/parse_http.go
I thought about adding more text/* types, but that quickly got complex as we already handle text/yaml and text/x-yaml so there would have to be exception lists.
I don't know if there are any application/* types that are actually JSON but don't indicate it; we could add them later.
Tested locally with akibox:
```
@app.get("/users/{user_id}/test")
async def get_user(user_id: str):
if user_id not in users:
raise HTTPException(status_code=404, detail="User not found")
return Response(content='{"user":"test", "value":17}',
media_type="application/vnd.api+json",
status_code=200)
```
> Handle any content type that has +json at the end as JSON.

- cmd/internal/pluginloader/load.go
- cmd/internal/pluginloader/precompiled_plugins.go
- plugin/README.md
Dynamically loaded plugins seem to have a lot of obstacles; this allows
us to include plugins from other repositories into the Akita CLI.
Updated README with instructions.
> Provide a way for plugins to be compiled into the Akita CLI.

- ci/circleci.go
The debug call used `"CIRCLE_CI_REPOSITORY_URL"` rather than `"CIRCLE_REPOSITORY_URL"`.
> Fix typo in CI tag debug logging

- cmd/internal/get/graph.go
- cmd/internal/get/timeline.go
- go.mod
- go.sum
- rest/learn_client.go
Also fixed a bug with 'get timeline' where the wrong default was being used.
Example usage:
```
mark@ubuntu:~/akita-cli$ bin/akita --domain staging.akita.software get graph --start 2021-09-30T00:00:00-05:00 akita-prod production --vertices=endpoints
[unknown]                      -> 10.0.187.101:10250                POST /exec/AbY97z1N
-> 10.0.187.101:10250                POST /exec/l2hDbH5r
-> 10.0.37.201:8080                   GET /
-> api.akita.software                 GET /v1/daemon/active
-> api.akita.software             OPTIONS /v1/daemon/active
-> api.akita.software                 GET /v1/integrations/github/repos
-> api.akita.software             OPTIONS /v1/integrations/github/repos
-> api.akita.software                 GET …
```
> Add 'akita get graph' to query service graph.

- apidump/apidump.go
- apidump/net.go
- cmd/internal/apidump/apidump.go
- cmd/internal/learn/cmd.go
- cmd/internal/learn/flags.go
- trace/dummy_collector.go
Anyone wishing to restore the old behaviour can use the hidden flag `--enable-outbound-collection`. When this flag is used, the user is warned that the flag might be removed in a future release.
> Disable collection of outbound witnesses by default

- apidump/apidump.go
- pcap/net_parse_test.go
- pcap/stream.go
Includes a (disabled) unit test demonstrating one way this can arise.
Added counters reporting number of such errors at the end of 'apidump'.
Question: is there a nice counter library we should be using?  Or is everything StatsD-based in the modern era?
> Remove error messages when an assembly context is nil.

- go.mod
- go.sum
- learn/parse_http.go
Depends on: https://github.com/akitasoftware/akita-ir/pull/6 and https://github.com/akitasoftware/akita-libs/pull/96
I'm wondering if this will cause us to spend a lot of time examining things like png or jpg images returned from an endpoint.
One mitigation is to tune MaxBufferedBody way, way down, it's currently at 5MB.
I didn't feel comfortable making the body a "None" in a "Oneof None String" field.  This will at least give us some information about whether small response bodies are identical.  But I'd be happy to come up with a different way of signaling "we didn't expect to understand the body format, so we didn't try."
> Handle HTTP and 'other' body types

- apidump/apidump.go
- apispec/har.go
- apispec/run.go
- cmd/internal/apidump/apidump.go
- cmd/internal/learn/cmd.go
- cmd/internal/learn/flags.go
- daemon/internal/cloud_client/cloud_client.go
- go.mod
- go.sum
- learn/kgx_processor.go
- learn/learn.go
- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/har_collector.go
- upload/run.go
Removed `--enable-outbound-collection`.
"Outbound" packets are now only captured during debugging, so the CLI can print summary statistics to the user.
> Disable collection and uploading of outbound witnesses

- cmd/internal/get/specs.go
- go.mod
- go.sum
#126 adopted a new format for `SpecInfo` that was not backwards compatible.  This PR bumps to a version of akita-libs with a backwards-compatible data structure.
> Revert "Update CLI to accept tag multisets from the backend (#126)" 

- trace/stats.go
- trace/stats_test.go
Fixes a bug where too many entries were added to telemetry summaries if the
entries had the same value for TCPPackets.
> Bugfix: Telemetry summaries had too many entries

- apispec/har.go
Existing exported functions handle processing HAR files.  This makes it possible to parse HAR data already loaded in memory.
> Export HAR-processing functions

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
Upload telemetry every 5 minutes while apidump is running.
I did not reset the counters; this, along with https://github.com/akitasoftware/superstar/pull/903, means that the packet count for the entire lifetime of the client will be shown.  (If we want to show a timeline or other derived data on the UI, we can compute the deltas between samples there.)
I did not enable this for `learn`, but it would not be hard to add the (hidden) flag there too.
> Send telemetry for the entire duration of the trace.

- apidump/apidump.go
Unless all collectors have failed, continue collecting traffic on healthy collectors/interfaces.
As an example, ephemeral interfaces are sometimes removed while the Akita client is collecting traffic, e.g. if a Docker container is stopped.  Rather than kill the CLI, we now continue collecting and summarize errors when packet collection is stopped.
> Continue packet collection after collector errors

- learn/parse_http.go
- pcap/net_parse.go
- trace/backend_collector.go
Increase "idle" connection timeout to 90 seconds.
Removed dump of reconstructed HTTP packets in hex form.
Added debugging messages about witness pairing.
Added debugging messages about TCP reassembly flushing and closing.
> Allow CLI to measure HTTP server latencies up to ~60s.

- apidiff/run.go
- apispec/run.go
- cmd/internal/apidiff/cmd.go
- cmd/internal/apidump/apidump.go
- cmd/internal/apispec/cmd.go
- cmd/internal/apispec/flags.go
- cmd/internal/get/graph.go
- cmd/internal/get/specs.go
- cmd/internal/get/timeline.go
- cmd/internal/get/traces.go
- cmd/internal/learn/cmd.go
- cmd/internal/learn/flags.go
- cmd/internal/login/login.go
- cmd/internal/man/apidiff_page.go
- cmd/internal/man/apidump_page.go
- cmd/internal/man/apispec_page.go
- cmd/internal/man/learn_page.go
- cmd/internal/man/setversion_page.go
- cmd/internal/man/upload_page.go
- cmd/internal/setversion/cmd.go
- cmd/internal/upload/cmd.go
- upload/run.go
- util/util.go
Deprecates the following commands, which are either no longer relevant or
replaced by the Akita app:
- apidiff
- apispec
- learn
- setversion
Deprecates the --deployment flag.  We recommend creating separate projects for
different deployment environments, e.g. my-project-staging and my-project-prod.
Deprecates the --service flag and replaces it with --project.
> Deprecate commands and flags

- learn/parse_http.go
We weren't applying decompressions in the correct order.
> Fixed bug in decompressing HTTP bodies

- .vscode/launch.json
- apidump/apidump.go
- cmd/root.go
- go.mod
- go.sum
- learn/learn_test.go
- learn/parse_http.go
- learn/util_test.go
- pcap/http_timing_test.go
- pcap/net_parse.go
- pcap/net_parse_test.go
- pcap/pcap_replay_test.go
- pcap/run.go
- pcap/stream.go
- pcap/stream_test.go
- pcap/util_test.go
- trace/backend_collector_test.go
- trace/rate_limit_test.go
Two improvements to memory usage:
* Don't buffer HTTP requests and responses during parsing. Previously, we were buffering the entire request/response so that it could be emitted as raw data when parsing failed. Instead we now just emit a count of how much data was consumed.
* Read HTTP payloads from a fixed-size buffer pool. Currently, this is a 20 MiB pool that gets allocated in 4-KiB chunks. These numbers were chosen arbitrarily.
I am concerned that this second change will cause the agent to stop reading full HTTP payloads when there are a lot of concurrent connections.
To evaluate the effects of these changes, 10 concurrent GET requests were continually made to a test service, once every <20 seconds for at least 6 hours. The response payload consisted of about 27 MiB of random JSON …
> Memory-usage improvements

- apidump/apidump.go
- cmd/internal/apidump/apidump.go
- cmd/internal/get/graph.go
- pcap/run.go
- Collection of TCP and TLS reports now disabled by default, since these are now being ignored by the back end. Use `akita apidump --report-tcp-and-tls` if you want these back for whatever reason.
- The subcommand `akita get graph` is now hidden, since the back end is no longer producing service graphs.
> Disabled deprecated features by default

- cmd/root.go
Also, make the -log-format flag visible.
> Print the version number on startup.

- learn/parse_http.go
- learn/parse_http_test.go
- trace/backend_collector.go
HTTP requests/responses may contain elements that result in duplicate Data items in the IR.  For example, requests may contain cookies with the same name and value (but different domains or paths, which is not currently stored in the IR).
Previously, duplicate items were interpreted as hash collisions, causing parsing to fail.  This PR amends that behavior to check for equality and fail only if items are different.
> Bugfix: Duplicate data items

- cmd/root.go
- telemetry/telemetry.go
This lets --domain work, but it makes it more complicated to capture the command line.
> Send telemetry after argument parsing.

- apidump/apidump.go
- apidump/summary.go
- cmd/internal/apidump/apidump.go
- go.mod
- go.sum
- trace/collector.go
Depends on https://github.com/akitasoftware/akita-libs/pull/159
Example output:
```
mark@ubuntu:~/akita-cli$ sudo -E bin/akita apidump --project mgg-test 
[INFO] Akita Agent 0.0.0
[INFO] Created new trace on Akita Cloud: akita://mgg-test:trace:lace-pig-d35eeeab
[INFO] Running learn mode on interfaces lo, ens33, docker0, br-a17c933efd5a
[WARNING] --filter flag is not set, this means that all network traffic is treated as your API traffic
[INFO] Send SIGINT (Ctrl-C) to stop...
[INFO] Printing packet capture statistics after 60 seconds of capture.
[INFO] ==================================================
[INFO] Packets per interface:
[INFO]                             TCP       HTTP      TLS      
[INFO]       interface       dir packets   req  resp hello   unk
[INFO]              lo …
```
> Report on count of TLS handshake messages.

- apidump/apidump.go
- apidump/summary.go
Attempt to explain what is going on for each port number.
Do not treat absence of --filter as a warning, since that is now our recommended default.
Existing full dump is only available with --debug, but the top N are still sent as telemetry.
> Highlight only top contributors instead of all packet counts.

- learn/json_preprocessor.go
- learn/json_preprocessor_test.go
- learn/parse_http.go
- learn/parse_http_test.go
The Go JSON parser rejects JSON strings that contain control characters (U+0000
- U+001F).  We'd like to be more permissive.  Rather than implementing our own parser, this PR adds a preprocessing step that removes unescaped control characters before invoking Go's JSON parser.
> Discard control characters when parsing JSON

- learn/json_preprocessor.go
- learn/json_preprocessor_test.go
When preprocessing JSON to remove control characters, replace escaped control characters with a backslash.  This ensures the JSON parser will interpret the escaped control character as an escaped backslash, rather than escaping the next character after the control character.
> Replace '\C' with '\\' instead of '\'

- apidump/summary.go
- go.mod
- go.sum
- pcap/run.go
- trace/collector.go
Depends on https://github.com/akitasoftware/akita-libs/pull/165
Example output:
```
[INFO] Printing packet capture statistics after 60 seconds of capture.
[INFO] TCP port  8080:   226 packets (53% of total), no HTTP/1.1 requests or responses, 10 HTTP/2 connection attempts. Akita cannot currently parse HTTP/2.
[INFO] TCP port  8000:   100 packets (23% of total), 10 HTTP requests, 10 HTTP responses, 0 TLS handshakes, 0 unparsed packets.
[INFO] TCP port   443:    84 packets (19% of total), no HTTP requests or responses; the data to this service could not be parsed.
```
or if there is a mixture (say, HTTP/1.1 upgrades:)
```
[INFO] Printing packet capture statistics after 60 seconds of capture.
[INFO] TCP port  8080:   124 packets (59% of total), 8 HTTP requests, 0 HTTP responses, 0 TLS …
```
> Recognize HTTP/2 traffic and mention it in the summary.

- apidump/defaults.go
- cmd/internal/akiflag/ignore.go
- cmd/internal/akiflag/rename.go
- cmd/internal/apidump/apidump.go
- cmd/internal/apispec/cmd.go
- cmd/internal/learn/cmd.go
- cmd/internal/learn/flags.go
We now also use Cobra's built-in facility for deprecating flags.
Factored command-line defaults for 'apidump' into symbolic constants, so they can be shared with 'learn'.
Removed auto-generation of CI-specific Akita-internal tags on learn sessions. No recent models have this tag, so it's not being used.
> Make 'learn' an alias for 'apidump'

- apidump/apidump.go
- apidump/net.go
Only suggest "use sudo" if not running as root.
There's also some customized messages if the interface list is empty, which... I don't really expect is possible?
> Explain permission errors in a context-sensitve way.

- learn/parse_http.go
- learn/parse_http_test.go
We treat authorization headers in requests differently than other headers; they're parsed into a special IR object that classifies the authorization kind.
Until now, we treated auth headers in responses the same way.  This PR changes HTTP parsing to treat authorization headers in responses the same as any other header.
> Treat authorization in response as a normal header

- go.mod
- go.sum
- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/report_buffer.go
Processing of witnesses now occurs when they are enqueued for upload. Additionally, the size of the buffer is now based on memory usage, rather than number of items.
> Refactor batching in backend collector

- apispec/defaults.go
- apispec/run.go
- cmd/internal/apidump/apidump.go
- cmd/internal/learn/cmd.go
- cmd/internal/learn/flags.go
- daemon/internal/cloud_client/cloud_client.go
- upload/run.go
Moved the definitions of default command-line parameter values out of `apidump` and into `apispec`, to avoid having `apispec` depend on `apidump`. This allows client code to import `apispec` without having to also pull in pcap.
> Move default definitions

- apidump/apidump.go
- apidump/summary.go
- apispec/run.go
- daemon/internal/cloud_client/cloud_client.go
- go.mod
- go.sum
- trace/backend_collector.go
- trace/backend_collector_test.go
- trace/report_buffer.go
- upload/run.go
Add and maintain a count of oversized witnesses in `client_telemetry.PacketCounts`. This is not reported to the user, but is reported to the back end as part of packet telemetry.
> Count oversized witnesses and report to back end

- apidump/apidump.go
- apidump/error.go
- apidump/error_test.go
- apidump/net.go
- architecture/architecture.go
- go.mod
- go.sum
- version/version.go
When running the Akita agent in a Docker container built for a different architecture than the host (e.g. built for amd64 but running on arm64), the agent fails to read any network interfaces with error messages of the form `SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: Function not implemented`.
This PR extends the agent to detect these errors and print a nicer error message for the user that indicates the underlying problem.  It also adds the target architecture to the `akita --version` output, e.g. `akita version 0.21.18 (09c7847085262f10ea9e2cd4bae280383970e5c1-dirty, arm64)`.
When running in Docker, the CLI output will look like this:
```
> docker run -e AKITA_API_KEY_ID -e AKITA_API_KEY_SECRET akitasoftware/cli:latest apidump --project akibox
WARNING: The requested image's platform …
```
> Detect when packet capture fails from architecture mismatch

- apidump/summary.go
- go.mod
- go.sum
- trace/collector.go
- trace/stats.go
- trace/stats_test.go
This PR adds per-host packet capture statistics for TLS handshakes and HTTP requests, which readily have the host available.  Per-host stats are uploaded with telemetry data and summarized as CLI output alongside per-port statistics.
This also adds hard limits on the number of ports, interfaces, and hosts that the CLI tracks for telemetry data.  The CLI is a long-running process, and our telemetry data monotonically increases.  We should consider capturing telemetry data in rolling windows in the future.  For now, I chose a limit of 10,000 each for ports, interfaces, and hosts; if we assume hosts and interfaces are ~10 bytes, then that maxes out at ~2Mb.  These are most useful in the first 60 seconds of running the CLI, so 10K should be more than enough.
Depends on …
> Report packet-capture statistics by host

- apidump/summary.go
- env/docker.go
Running the Akita agent in Docker Desktop (macOS or Windows) will fail to capture traffic to services running on the host – rather than sharing the host networking stack, Docker Desktop runs the daemon in a VM.  Docker users are instructed to use host.internal.docker to communicate with the host.
We can use the presence of that DNS name to detect if we're running in a container with Docker Desktop.  If so, suggest using the native macOS binary if the agent fails to capture traffic.
I'll add this to the telemetry in a future PR.
Here's the output when running the Akita agent in a Docker container on Docker Desktop.  The last INFO line is not present when running the Docker container on a Linux host.
```
[INFO] Send SIGINT (Ctrl-C) to stop...
[INFO] Printing packet capture statistics after …
```
> Help when running in Docker Desktop

- apidump/apidump.go
- apidump/health_check.go
- cmd/internal/apidump/apidump.go
This adds a server to the `apidump` command which responds to health check requests sent from the Docker extension.
> Add health check utility for Docker Extension

- cmd/internal/ecs/add.go
- cmd/internal/ecs/aws_api.go
- cmd/internal/ecs/aws_api_names.go
- cmd/internal/ecs/ecs.go
Refactored calls to ListFoo/DescribeFoo into a template function.
All command line options are supported, for both interactive and non-interactive mode.
Display the selected objects at the end and prompt for confirmation.
> Select task definition to modify and service to update.

- cmd/internal/ecs/add.go
- cmd/internal/ecs/aws_api.go
- cmd/internal/ecs/aws_api_secret.go
- deployment/deployment.go
- go.mod
- go.sum
Check whether the task definition already contains an Akita container, or the tag we will add.
The code to create an AWS secret is disabled for now, because using the secret requires changes to the assigned role.
Recognize ECS-specific environment variables and tag the trace.
Depends on https://github.com/akitasoftware/akita-libs/pull/177 for the new tags.
Verified that the new task definition works by upgrading the service in the ECS console.
> Register a modified ECS task definition.

- cmd/internal/ecs/add.go
- cmd/internal/ecs/aws_api.go
Add permission handling to DescribeTaskDefinition error.
Previous step from getTask should be getCluster.
Report on correct error when tagging.
> Fix bugs discovered during permissions testing:

- apidump/apidump.go
- apispec/defaults.go
- cmd/internal/apidump/apidump.go
- cmd/internal/learn/cmd.go
- go.mod
- go.sum
- main.go
- usage/usage.go
When `/proc` files are available (e.g. most Linux flavors), include the Akita CLI's CPU and memory usage with packet capture telemetry.
Depends on https://github.com/akitasoftware/akita-libs/pull/181.
> Report CLI CPU/memory usage with telemetry

- cmd/root.go
- rest/base_client.go
- rest/http.go
Would like to have a user who is blocked try this out.
Adds ability to specify an alternate server name, negative and positive testing:
```
mark@ubuntu:~/akita-cli$ sudo -E bin/akita apidump --server-tls-name api.akitasoftare.com --project mgg-test --debug
[INFO] Akita Agent 0.0.0
[ERROR]  request failed [error Get "https://api.akita.software/v1/services": x509: certificate is valid for api.akita.software, not api.akitasoftare.com method GET url https://api.akita.software/v1/services]
mark@ubuntu:~/akita-cli$ sudo -E bin/akita apidump --server-tls-name api.akita.software --project mgg-test --debug.
[INFO] Akita Agent 0.0.0
[DEBUG] Project name "mgg-test" is "svc_14kS9tQ5U2gS98De4TZIwc"
...
```
Adds configuration flag for proxy, accepts either URL or host:port.
```
mark@ubuntu:~/akita-cli$ …
```
> Allow user to use a proxy, an alternate server name, or skip TLS

- integrations/nginx/backend.go
I did not edit akita-libs to add this as a source type.
> Add a source tag indicating the trace comes from the NGINX integration

- cmd/internal/cmderr/checks.go
- cmd/internal/ecs/ecs.go
- cmd/internal/kube/kube.go
- cmd/internal/kube/secret.go
- cmd/internal/kube/secret_test.go
- cmd/internal/kube/template.go
- cmd/internal/kube/template/akita-secret.tmpl
- cmd/internal/kube/test_resource/akita-secret.yml
- cmd/root.go
- learn/parse_http_test.go
- pcap/stream_test.go
- telemetry/telemetry.go
This adds a new command `akita kube secret` which generates a Kubernetes secret configuration file that stores a user's base-64 encoded Akita API credentials.
To simplify file generation, I've used go's built-in templating utilities; `akita-secret.tmpl` is used as the template for creating the secret.
Example usage:
```
% ./bin/akita kube secret -n test -o ./tmp/deployments/configs/akita-secrets.yml
[INFO] Akita Agent 0.0.0
[INFO] Generated Kubernetes secret config to ./tmp/deployments/configs/akita-secrets.yml                                                                                                               
% less ./tmp/deployments/configs/akita-secrets.yml 
apiVersion: v1
kind: Secret
metadata:
name: akita-secrets
namespace: test
type: Opaque
data:
akita-api-key: …
```
> Add command to generate Kubernetes Secrets

- cmd/internal/kube/kube.go
- cmd/internal/kube/secret.go
This fixes an issue where the `kube` command did not show a help message as intended. For better clarity, I've also made some minor updates to the `kube secret` command description.
> Fix help messages for kube commands

- cfg/credentials.go
- cmd/internal/cmderr/checks.go
- cmd/internal/ecs/ecs.go
- cmd/internal/kube/inject.go
- cmd/internal/kube/secret.go
- cmd/internal/kube/secret_test.go
- cmd/internal/kube/template/postman-secret.tmpl
- cmd/internal/kube/test_resource/postman-secret.yml
* Add support for 3 Postman flags in `kubectl inject` command, namely --collection, --key , and --environment
* Setting postman API key as an k8s secret
* Passing other two params normally in args
* Added env var support for postman API key
* Other refactoring and typos fix wherever necessary
> [OBS-37|38] Add support for Postman flags in `kube inject` command

- cmd/internal/kube/inject.go
- cmd/root.go
- rest/base_client.go
- rest/domain.go
If a non-default domain is used, include it in the injected container's
command line.
Simplify the logic for deciding when to prefix "api" onto the domain.
> Select the default domain based on a Postman environment

- cmd/internal/kube/inject.go
- cmd/internal/kube/secret.go
- util/util.go
These override PersistentPreRun (to avoid logging output) which means that the rest.Domain value was not getting set.
> Call DefaultDomain() in kube subcommands.

- cfg/credentials.go
- rest/front_client.go
- rest/interface.go
- rest/models.go
- util/util.go
Response of `createService` endpoint is not handled properly which is causing serviceId being set to be `srv_000...`
Which is causing error while sending witness data to backend.
> [OBS-138] fix: handle createService response properly

- rest/front_client.go
- rest/interface.go
- util/util.go
Front determines the environment to use based on the X-Postman-Env header; only admins can create a service in a different environment.
> Remove 'env' parameter from CreateService.

- rest/models.go
Currently if we don't send any value for env then it is sending an empty string which is throwing error in BE due to wrong enum type.
So need to add `omitempty` in model
> fix: omit empty env value

- util/util.go
* Since we are moving away from the environment flag, whenever we try to get `postman_env's` value we get the empty string `""`
* This is causing an issue while checking for the mapping between service and collectionId, cause we will be getting environment value also from BE and hence `strings.EqualFold(svcEnv, env)` will never be true and we will create a new service every time cli starts
* So in this PR we have removed this check of env vars from here. We don't really need this check because after 9/15 release  `postman_env` field will be irrelevant (every environment has its own infra) and AFAIK, for the existing stage services there are no collections with the same Id within an org
**PS:** One other option we have is, setting a default value for `postman_env` in `initCreds()` …
> chore: remove env check while looping collnId and serviceId mapping

- cmd/internal/kube/inject.go
This PR updates the injector to Akita's ECR repository instead of DockerHub. This should resolve [OBS-183](https://postmanlabs.atlassian.net/jira/software/projects/OBS/boards/778?assignee=712020%3Af32f8c82-558b-4b4f-9cee-b82d08937c9b&selectedIssue=OBS-183)
> [OBS-183] Update injector to reference ECR

- .github/workflows/security-scan.yaml
- .gitignore
- Makefile
- apidump/apidump.go
- apidump/net.go
- apidump/summary.go
- apispec/har.go
- cmd/internal/apidump/apidump.go
- cmd/internal/cmderr/checks.go
- cmd/internal/ecs/add.go
- cmd/internal/ecs/ecs.go
- cmd/internal/get/cmd.go
- cmd/internal/kube/inject.go
- cmd/internal/kube/kube.go
- cmd/internal/kube/secret.go
- cmd/root.go
- daemon/internal/cloud_client/cloud_client.go
- integrations/nginx/schema.go
- rest/http.go
- telemetry/telemetry.go
- trace/report_buffer.go
- usage/usage.go
- useragent/useragent.go
- useragent/useragent_test.go
All environment variables are still Akita-branded, but we now recognize `POSTMAN_LC_AGENT_DISABLE_TELEMETRY` in addition to the existing `AKITA_DISABLE_TELEMETRY`.
> Partial Postman rebrand

- apidump/apidump.go
- cmd/internal/kube/inject.go
- rest/models.go
- util/util.go
* Create a new model to parse error response
* Handle the 409 conflict case. Check for error message and call get services again 
* Try only one time after that bail out with error
* Other small fixes: Add to cache after create service flow, small model change
> [OBS-137] Handle 409 response of create service to again check for service

- cmd/internal/ecs/add.go
- cmd/internal/ecs/ecs.go
> Add collection flag for postman ECS agent

- cfg/credentials.go
- telemetry/telemetry.go
Previously we were calling /v1/users to get an email to use as a distinct ID only when an Akita API Key was present.
> OBS-419: Fix distinct ID for Postman API key users.

- cmd/internal/ec2/add.go
- Handle the case when linux setup command is run again on a system on which it was previously used.
- There can be three possibilities
- systemd service exists and is enabled: Ask user if old values should be over-written with current input
- systemd service exists and is disabled: Ask user if old values should be over-written with current input and enable the service
- systemd service doesn't exist: Proceed with normal flow
Ticket: https://postmanlabs.atlassian.net/browse/OBS-407
> [OBS-407]Linux agent: Handle reconfiguration

- cmd/root.go
- go.mod
- go.sum
- telemetry/telemetry.go
- trace/backend_collector_test.go
* Replace Segment related keys and mentioned with Amplitude Keys and configs
* Updated few event names to make them consistent in Amplitude
> [POA-41] Update analytics functions to support amplitude functions

- cmd/root.go
- rest/learn_client.go
* These changes are to make integration tests working
* Exposed `specs get` command
* Switched `get-spec-version` and `get-specs` to `v2/agent` since they are needed in `specs get` command
> [POA-748] expose legacy command

- cmd/root.go
Fixes an annoyance introduced in #258.
Also accept 'colour' for log format.
> POA-894 Fix default log format

- go.mod
- go.sum
- telemetry/telemetry.go
* Refactored `distinctID()` function in `telemetry.go` to have both `user_id` and `team_id` instead of only `distinct_id`.
* We will be sending both `user_id` and `team_id` as base properties along with other event specific properties
* Done changes in the event names to combine various events with a single generic event, each separate event can be identified by the properties
More info on events refactoring: https://docs.google.com/spreadsheets/d/19u7kHBunBLcbtfQjTvrrnQ_cgiOOEKYO9lhWviuCuk8/edit?usp=sharing
> [POA-877|669] Refactor telemetry events

- aws_utils/cloudformation/ecs/types.go
- aws_utils/console/ecs/types.go
- cmd/internal/ecs/add.go
- cmd/internal/ecs/ecs.go
- cmd/root.go
- go.mod
- go.sum
Added `ecs cf-fragment` subcommand for printing an AWS CloudFormation fragment for adding the agent to ECS as a sidecar.
Added `ecs task-def` subcommand for printing a task definition that can be added to an ECS cluster to run the agent as a daemon in host-networking mode on every EC2 instance in the cluster.
Removed `--collection` from `ecs` subcommands.
> POA-114 Add ecs cf-fragment and ecs task-def subcommands

- cmd/internal/ecs/add.go
Plan: https://postmanlabs.atlassian.net/wiki/spaces/PO/pages/5053218962/Plan+Insights+Agent+ECS+and+other+tasks+for+supporting+50+users#Alert-user-about-the-wrong-network-mode-in-ecs-add.1
Added bridge networking mode check in the `getTaskState()` function in the `ecs add` command and exit installation with proper error message 
---
Reviewers:
* Primary: @shreys7 
* Secondary: @mgritter
> [POA-1089] Add check for bridge networking in 'ecs add' command

- cmd/internal/ecs/add.go
We missed the bridge networking check in the `loadTaskFromFlag()` function, where we use the task value passed as the `--task` flag instead of asking interactively.
Also, if a user is running `ecs add` in interactive mode, ask for the task state again instead of erroring out.
Add the checks to this PR.
> [POA-1809] Add bridge mode check in taskFlag function
